#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <unordered_map>
#include "interpreter/interpreter.h"
#include "interpreter/environment.h"
#include "features/callable.h"
#include "lexer/lexer.h"
#include "parser/parser.h"

static void writeHeader(std::ostream& out, const std::string& title) {
    out << "# " << title << "\n\n";
    out << "This file is generated by claw_api_gen. It lists globals and native functions available in ClawScript.\n\n";
}

static void writeFunction(std::ostream& out, const std::string& name, int arity) {
    out << "- " << name << "(";
    for (int i = 0; i < arity; ++i) {
        out << "arg" << (i + 1);
        if (i + 1 < arity) out << ", ";
    }
    out << ")\n";
}

int main(int argc, char** argv) {
    std::string outPath;
    if (argc > 1) outPath = argv[1];
    claw::Interpreter interp;
    auto globals = interp.getGlobals();
    std::vector<std::string> names;
    globals->forEachKey([&](std::string_view sv) {
        names.emplace_back(sv);
    });
    std::ostringstream md;
    writeHeader(md, "ClawScript API Reference (Generated)");
    md << "## Global Functions\n\n";
    for (const auto& n : names) {
        claw::Value v = globals->get(n);
        if (claw::isCallable(v)) {
            auto fn = claw::asCallable(v);
            int ar = fn ? fn->arity() : 0;
            if (ar < 0) {
                md << "- " << n << "(...)\n";
            } else {
                writeFunction(md, n, ar);
            }
        } else {
            md << "- " << n << "\n";
        }
    }
    if (outPath.empty()) {
        std::cout << md.str();
    } else {
        std::ofstream out(outPath, std::ios::binary | std::ios::trunc);
        out << md.str();
    }
    return 0;
}
