set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER x86_64-linux-musl-gcc)
set(CMAKE_CXX_COMPILER x86_64-linux-musl-g++)
set(CMAKE_AR x86_64-linux-musl-ar)
set(CMAKE_RANLIB x86_64-linux-musl-ranlib)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static -O3")
